package callofcthulhuDB.entity;
// Generated 23 lut 2020, 09:37:02 by Hibernate Tools 4.3.1



/**
 * FirstName generated by hbm2java
 */
public class FirstName  implements java.io.Serializable {


     private Integer id;
     private String firstName;
     private String sex;

    public FirstName() {
    }

	
    public FirstName(String firstName) {
        this.firstName = firstName;
    }
    public FirstName(String firstName, String sex) {
       this.firstName = firstName;
       this.sex = sex;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }




}


