package callofcthulhuDB.entity;
// Generated 23 lut 2020, 09:37:02 by Hibernate Tools 4.3.1



/**
 * Profession generated by hbm2java
 */
public class Profession  implements java.io.Serializable {


     private Integer id;
     private String profession;
     private Integer accounting;
     private Integer anthropology;
     private Integer appraise;
     private Integer archeology;
     private Integer craft;
     private Integer craft2nd;
     private Integer craft3rd;
     private Integer charm;
     private Integer climb;
     private Integer creditRating;
     private Integer cthulhuMythos;
     private Integer disguise;
     private Integer dodge;
     private Integer drive;
     private Integer electricalRepair;
     private Integer fastTalk;
     private Integer fighting;
     private Integer fighting2nd;
     private Integer fighting3rd;
     private Integer handgun;
     private Integer rifle;
     private Integer rifle2nd;
     private Integer firstAid;
     private Integer history;
     private Integer intimidate;
     private Integer jump;
     private Integer languageOther;
     private Integer languageOther2nd;
     private Integer languageOther3rd;
     private Integer languageOwn;
     private Integer law;
     private Integer libraryUse;
     private Integer listen;
     private Integer locksmithing;
     private Integer mechanicalRepair;
     private Integer medicine;
     private Integer naturalWorld;
     private Integer navigate;
     private Integer occult;
     private Integer opHvMachine;
     private Integer persuade;
     private Integer pilot;
     private Integer psychology;
     private Integer psychoanalysis;
     private Integer riding;
     private Integer science;
     private Integer science2nd;
     private Integer science3rd;
     private Integer sleightOfHand;
     private Integer spotHidden;
     private Integer stealth;
     private Integer survival;
     private Integer swim;
     private Integer throw_;
     private Integer track;
     private Integer other1st;
     private Integer other2nd;
     private Integer other3rd;
     private Integer other4th;
     private Integer other5th;

    public Profession() {
    }

	
    public Profession(String profession) {
        this.profession = profession;
    }
    public Profession(String profession, Integer accounting, Integer anthropology, Integer appraise, Integer archeology, Integer craft, Integer craft2nd, Integer craft3rd, Integer charm, Integer climb, Integer creditRating, Integer cthulhuMythos, Integer disguise, Integer dodge, Integer drive, Integer electricalRepair, Integer fastTalk, Integer fighting, Integer fighting2nd, Integer fighting3rd, Integer handgun, Integer rifle, Integer rifle2nd, Integer firstAid, Integer history, Integer intimidate, Integer jump, Integer languageOther, Integer languageOther2nd, Integer languageOther3rd, Integer languageOwn, Integer law, Integer libraryUse, Integer listen, Integer locksmithing, Integer mechanicalRepair, Integer medicine, Integer naturalWorld, Integer navigate, Integer occult, Integer opHvMachine, Integer persuade, Integer pilot, Integer psychology, Integer psychoanalysis, Integer riding, Integer science, Integer science2nd, Integer science3rd, Integer sleightOfHand, Integer spotHidden, Integer stealth, Integer survival, Integer swim, Integer throw_, Integer track, Integer other1st, Integer other2nd, Integer other3rd, Integer other4th, Integer other5th) {
       this.profession = profession;
       this.accounting = accounting;
       this.anthropology = anthropology;
       this.appraise = appraise;
       this.archeology = archeology;
       this.craft = craft;
       this.craft2nd = craft2nd;
       this.craft3rd = craft3rd;
       this.charm = charm;
       this.climb = climb;
       this.creditRating = creditRating;
       this.cthulhuMythos = cthulhuMythos;
       this.disguise = disguise;
       this.dodge = dodge;
       this.drive = drive;
       this.electricalRepair = electricalRepair;
       this.fastTalk = fastTalk;
       this.fighting = fighting;
       this.fighting2nd = fighting2nd;
       this.fighting3rd = fighting3rd;
       this.handgun = handgun;
       this.rifle = rifle;
       this.rifle2nd = rifle2nd;
       this.firstAid = firstAid;
       this.history = history;
       this.intimidate = intimidate;
       this.jump = jump;
       this.languageOther = languageOther;
       this.languageOther2nd = languageOther2nd;
       this.languageOther3rd = languageOther3rd;
       this.languageOwn = languageOwn;
       this.law = law;
       this.libraryUse = libraryUse;
       this.listen = listen;
       this.locksmithing = locksmithing;
       this.mechanicalRepair = mechanicalRepair;
       this.medicine = medicine;
       this.naturalWorld = naturalWorld;
       this.navigate = navigate;
       this.occult = occult;
       this.opHvMachine = opHvMachine;
       this.persuade = persuade;
       this.pilot = pilot;
       this.psychology = psychology;
       this.psychoanalysis = psychoanalysis;
       this.riding = riding;
       this.science = science;
       this.science2nd = science2nd;
       this.science3rd = science3rd;
       this.sleightOfHand = sleightOfHand;
       this.spotHidden = spotHidden;
       this.stealth = stealth;
       this.survival = survival;
       this.swim = swim;
       this.throw_ = throw_;
       this.track = track;
       this.other1st = other1st;
       this.other2nd = other2nd;
       this.other3rd = other3rd;
       this.other4th = other4th;
       this.other5th = other5th;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getProfession() {
        return this.profession;
    }
    
    public void setProfession(String profession) {
        this.profession = profession;
    }
    public Integer getAccounting() {
        return this.accounting;
    }
    
    public void setAccounting(Integer accounting) {
        this.accounting = accounting;
    }
    public Integer getAnthropology() {
        return this.anthropology;
    }
    
    public void setAnthropology(Integer anthropology) {
        this.anthropology = anthropology;
    }
    public Integer getAppraise() {
        return this.appraise;
    }
    
    public void setAppraise(Integer appraise) {
        this.appraise = appraise;
    }
    public Integer getArcheology() {
        return this.archeology;
    }
    
    public void setArcheology(Integer archeology) {
        this.archeology = archeology;
    }
    public Integer getCraft() {
        return this.craft;
    }
    
    public void setCraft(Integer craft) {
        this.craft = craft;
    }
    public Integer getCraft2nd() {
        return this.craft2nd;
    }
    
    public void setCraft2nd(Integer craft2nd) {
        this.craft2nd = craft2nd;
    }
    public Integer getCraft3rd() {
        return this.craft3rd;
    }
    
    public void setCraft3rd(Integer craft3rd) {
        this.craft3rd = craft3rd;
    }
    public Integer getCharm() {
        return this.charm;
    }
    
    public void setCharm(Integer charm) {
        this.charm = charm;
    }
    public Integer getClimb() {
        return this.climb;
    }
    
    public void setClimb(Integer climb) {
        this.climb = climb;
    }
    public Integer getCreditRating() {
        return this.creditRating;
    }
    
    public void setCreditRating(Integer creditRating) {
        this.creditRating = creditRating;
    }
    public Integer getCthulhuMythos() {
        return this.cthulhuMythos;
    }
    
    public void setCthulhuMythos(Integer cthulhuMythos) {
        this.cthulhuMythos = cthulhuMythos;
    }
    public Integer getDisguise() {
        return this.disguise;
    }
    
    public void setDisguise(Integer disguise) {
        this.disguise = disguise;
    }
    public Integer getDodge() {
        return this.dodge;
    }
    
    public void setDodge(Integer dodge) {
        this.dodge = dodge;
    }
    public Integer getDrive() {
        return this.drive;
    }
    
    public void setDrive(Integer drive) {
        this.drive = drive;
    }
    public Integer getElectricalRepair() {
        return this.electricalRepair;
    }
    
    public void setElectricalRepair(Integer electricalRepair) {
        this.electricalRepair = electricalRepair;
    }
    public Integer getFastTalk() {
        return this.fastTalk;
    }
    
    public void setFastTalk(Integer fastTalk) {
        this.fastTalk = fastTalk;
    }
    public Integer getFighting() {
        return this.fighting;
    }
    
    public void setFighting(Integer fighting) {
        this.fighting = fighting;
    }
    public Integer getFighting2nd() {
        return this.fighting2nd;
    }
    
    public void setFighting2nd(Integer fighting2nd) {
        this.fighting2nd = fighting2nd;
    }
    public Integer getFighting3rd() {
        return this.fighting3rd;
    }
    
    public void setFighting3rd(Integer fighting3rd) {
        this.fighting3rd = fighting3rd;
    }
    public Integer getHandgun() {
        return this.handgun;
    }
    
    public void setHandgun(Integer handgun) {
        this.handgun = handgun;
    }
    public Integer getRifle() {
        return this.rifle;
    }
    
    public void setRifle(Integer rifle) {
        this.rifle = rifle;
    }
    public Integer getRifle2nd() {
        return this.rifle2nd;
    }
    
    public void setRifle2nd(Integer rifle2nd) {
        this.rifle2nd = rifle2nd;
    }
    public Integer getFirstAid() {
        return this.firstAid;
    }
    
    public void setFirstAid(Integer firstAid) {
        this.firstAid = firstAid;
    }
    public Integer getHistory() {
        return this.history;
    }
    
    public void setHistory(Integer history) {
        this.history = history;
    }
    public Integer getIntimidate() {
        return this.intimidate;
    }
    
    public void setIntimidate(Integer intimidate) {
        this.intimidate = intimidate;
    }
    public Integer getJump() {
        return this.jump;
    }
    
    public void setJump(Integer jump) {
        this.jump = jump;
    }
    public Integer getLanguageOther() {
        return this.languageOther;
    }
    
    public void setLanguageOther(Integer languageOther) {
        this.languageOther = languageOther;
    }
    public Integer getLanguageOther2nd() {
        return this.languageOther2nd;
    }
    
    public void setLanguageOther2nd(Integer languageOther2nd) {
        this.languageOther2nd = languageOther2nd;
    }
    public Integer getLanguageOther3rd() {
        return this.languageOther3rd;
    }
    
    public void setLanguageOther3rd(Integer languageOther3rd) {
        this.languageOther3rd = languageOther3rd;
    }
    public Integer getLanguageOwn() {
        return this.languageOwn;
    }
    
    public void setLanguageOwn(Integer languageOwn) {
        this.languageOwn = languageOwn;
    }
    public Integer getLaw() {
        return this.law;
    }
    
    public void setLaw(Integer law) {
        this.law = law;
    }
    public Integer getLibraryUse() {
        return this.libraryUse;
    }
    
    public void setLibraryUse(Integer libraryUse) {
        this.libraryUse = libraryUse;
    }
    public Integer getListen() {
        return this.listen;
    }
    
    public void setListen(Integer listen) {
        this.listen = listen;
    }
    public Integer getLocksmithing() {
        return this.locksmithing;
    }
    
    public void setLocksmithing(Integer locksmithing) {
        this.locksmithing = locksmithing;
    }
    public Integer getMechanicalRepair() {
        return this.mechanicalRepair;
    }
    
    public void setMechanicalRepair(Integer mechanicalRepair) {
        this.mechanicalRepair = mechanicalRepair;
    }
    public Integer getMedicine() {
        return this.medicine;
    }
    
    public void setMedicine(Integer medicine) {
        this.medicine = medicine;
    }
    public Integer getNaturalWorld() {
        return this.naturalWorld;
    }
    
    public void setNaturalWorld(Integer naturalWorld) {
        this.naturalWorld = naturalWorld;
    }
    public Integer getNavigate() {
        return this.navigate;
    }
    
    public void setNavigate(Integer navigate) {
        this.navigate = navigate;
    }
    public Integer getOccult() {
        return this.occult;
    }
    
    public void setOccult(Integer occult) {
        this.occult = occult;
    }
    public Integer getOpHvMachine() {
        return this.opHvMachine;
    }
    
    public void setOpHvMachine(Integer opHvMachine) {
        this.opHvMachine = opHvMachine;
    }
    public Integer getPersuade() {
        return this.persuade;
    }
    
    public void setPersuade(Integer persuade) {
        this.persuade = persuade;
    }
    public Integer getPilot() {
        return this.pilot;
    }
    
    public void setPilot(Integer pilot) {
        this.pilot = pilot;
    }
    public Integer getPsychology() {
        return this.psychology;
    }
    
    public void setPsychology(Integer psychology) {
        this.psychology = psychology;
    }
    public Integer getPsychoanalysis() {
        return this.psychoanalysis;
    }
    
    public void setPsychoanalysis(Integer psychoanalysis) {
        this.psychoanalysis = psychoanalysis;
    }
    public Integer getRiding() {
        return this.riding;
    }
    
    public void setRiding(Integer riding) {
        this.riding = riding;
    }
    public Integer getScience() {
        return this.science;
    }
    
    public void setScience(Integer science) {
        this.science = science;
    }
    public Integer getScience2nd() {
        return this.science2nd;
    }
    
    public void setScience2nd(Integer science2nd) {
        this.science2nd = science2nd;
    }
    public Integer getScience3rd() {
        return this.science3rd;
    }
    
    public void setScience3rd(Integer science3rd) {
        this.science3rd = science3rd;
    }
    public Integer getSleightOfHand() {
        return this.sleightOfHand;
    }
    
    public void setSleightOfHand(Integer sleightOfHand) {
        this.sleightOfHand = sleightOfHand;
    }
    public Integer getSpotHidden() {
        return this.spotHidden;
    }
    
    public void setSpotHidden(Integer spotHidden) {
        this.spotHidden = spotHidden;
    }
    public Integer getStealth() {
        return this.stealth;
    }
    
    public void setStealth(Integer stealth) {
        this.stealth = stealth;
    }
    public Integer getSurvival() {
        return this.survival;
    }
    
    public void setSurvival(Integer survival) {
        this.survival = survival;
    }
    public Integer getSwim() {
        return this.swim;
    }
    
    public void setSwim(Integer swim) {
        this.swim = swim;
    }
    public Integer getThrow_() {
        return this.throw_;
    }
    
    public void setThrow_(Integer throw_) {
        this.throw_ = throw_;
    }
    public Integer getTrack() {
        return this.track;
    }
    
    public void setTrack(Integer track) {
        this.track = track;
    }
    public Integer getOther1st() {
        return this.other1st;
    }
    
    public void setOther1st(Integer other1st) {
        this.other1st = other1st;
    }
    public Integer getOther2nd() {
        return this.other2nd;
    }
    
    public void setOther2nd(Integer other2nd) {
        this.other2nd = other2nd;
    }
    public Integer getOther3rd() {
        return this.other3rd;
    }
    
    public void setOther3rd(Integer other3rd) {
        this.other3rd = other3rd;
    }
    public Integer getOther4th() {
        return this.other4th;
    }
    
    public void setOther4th(Integer other4th) {
        this.other4th = other4th;
    }
    public Integer getOther5th() {
        return this.other5th;
    }
    
    public void setOther5th(Integer other5th) {
        this.other5th = other5th;
    }




}


