package callofcthulhuDB.entity;
// Generated 25 lut 2020, 05:02:34 by Hibernate Tools 4.3.1



/**
 * Profession generated by hbm2java
 */
public class Profession  implements java.io.Serializable {


     private Integer id;
     private String profession;
     private int minAge;
     private int maxAge;

    public Profession() {
    }

    public Profession(String profession, int minAge, int maxAge) {
       this.profession = profession;
       this.minAge = minAge;
       this.maxAge = maxAge;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getProfession() {
        return this.profession;
    }
    
    public void setProfession(String profession) {
        this.profession = profession;
    }
    public int getMinAge() {
        return this.minAge;
    }
    
    public void setMinAge(int minAge) {
        this.minAge = minAge;
    }
    public int getMaxAge() {
        return this.maxAge;
    }
    
    public void setMaxAge(int maxAge) {
        this.maxAge = maxAge;
    }




}


